import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import Link from 'next/link';

const noto = Noto_Sans_JP({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <div className='flex items-center justify-center py-6'>
          <Link href="/"><p className='text-2xl font-bold'>Feign 情報局</p></Link>
        </div>
        {children}
      </body>
    </html>
  );
}
